version: '3.8'
services:
  app:
    image: pulkitgsenkusha/product:v2.0.0
    ports:
      - "8000:8000"  
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=db_name
      - DB_USER=postgres
      - DB_PASSWORD=ur_password
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ur_password
      - POSTGRES_DB=db_name
    ports:
      - "5432:5432"  
